name: mobile
description: Silver Path mobile app
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_advanced_networkimage: ^0.4.15
  json_annotation: ^2.4.0
  enum_to_string: ^1.0.7
  flutter_svg: ^0.12.0
  flip_card: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.1
  json_serializable: ^3.0.0
flutter:
  uses-material-design: true
  fonts:
    - family:  SilverPathIcons
      fonts:
      - asset: fonts/SilverPathIcons.ttf
    - family: Meath
      fonts:
      - asset: fonts/Meath.ttf
    - family: Montserrat
      fonts:
      - asset: fonts/Montserrat-Regular.ttf
  assets:
    - assets/
